import React from "react";
import {Helmet} from "react-helmet";
import "./Home.css";
import "./sozlesmeler.css";

export class IyzicoSaticiSozlesmesi extends React.Component {
    componentDidMount() {
        window.scrollTo(0, 0);
      }
    
    render() {
        return (
            <React.Fragment>
                 <Helmet>
                <meta charSet="utf-8" />
                <title>DogGO - Türkiye'nin İlk ve Tek Köpek Gezdirme Uygulaması</title>
                <link rel="canonical" href="https://www.doggoapp.com/Iyzico-Satici-Sozlesmesi" />
                <meta name="description" content="DogGO, mobil uygulama üzerinden köpek sahiplerine güvenli ve profesyonel şekilde köpek gezdirme ve bakım hizmeti sunan Türkiye'deki ilk şirkettir."></meta>

            </Helmet>
                <section className=" sec-header soz-1-bg doggo-color-thi" id="1">
                        <h1 className="soz-h1-sty">Iyzico Iyzibazaar Satıcı Sözleşmesi</h1>
                </section>
                        <section>
                        <div className="container">
                                <h1>iyzibazaar SATICI ÖDEME HİZMETİ ÇERÇEVE SÖZLEŞMESİ</h1>
                                <p>1. TARAFLAR</p>
                                <p>İşbu iyzibazaar Alıcı Ödeme Hizmeti Çerçeve Sözleşmesi, aşağıda bilgileri yer alan iyzico ile işbu Sözleşme’deki hizmetlerden faydalanmak isteyen Satıcı arasında akdedilmiştir.</p>
                                <p>iyzico:</p>
                                <p>Unvan: iyzi Ödeme ve Elektronik Para Hizmetleri A.Ş.</p>
                                <p>Adres: Burhaniye Mah. Atilla Sok. No:7 Üsküdar İstanbul</p>
                                <p>Vergi Daire ve No.: Üsküdar Vergi Dairesi - 483 034 31 57</p>
                                <p>Telefon No: +90 216 599 01 00</p>
                                <p>iyzico ve Satıcı bundan böyle birlikte “Taraflar”, ayrı ayrı “Taraf” olarak anılacaktır.</p>
                                <p>2. TANIMLAR</p>
                                <p>Alıcı :&nbsp; İnternet Sitesi üzerinden işbu Sözleşme kapsamında sunulan servisler aracılığı ile mal veya hizmet alımı yapan ve bu amaçla Servis’ten faydalanan Son Kullanıcı</p>
                                <p>Hassas Ödeme Verisi : Alıcı tarafından ödeme emrinin verilmesinde veya Alıcı’nın kimliğinin doğrulanmasında kullanılan, ele geçirilmesi veya değiştirilmesi halinde olandırıcılık ya da kullanıcılar adına sahte işlem yapılmasına imkan verebilecek şifre, güvenlik sorusu, sertifika, şifreleme anahtarı ile PIN, kart numarası, son kullanma
                                    tarihi, CVV2, CVC2 kodu gibi veriler</p>
                                <p>Hatalı/Yetkisiz İşlem : Hatalı bir şekilde veya Alıcı’nın talimatı dışında gerçekleştirilen Ödeme İşlemi</p>
                                <p>İnternet Sitesi : İnternet üzerinden ticarî faaliyet yürüten Pazaryeri’ne ait ve, Pazaryeri veya Satıcı tarafından mal veya hizmetlerin satışa sunulması için kullanılan internet sitesi</p>
                                <p>iyzico : İletişim bilgileri işbu Sözleşme’nin 1. maddesinde belirtilen ve işbu Sözleşme'de ödeme hizmeti sağlayıcı taraf olan iyzi Ödeme ve Elektronik Para Hizmetleri Anonim Şirketi</p>
                                <p>iyzibazaar : Son Kullanıcılar’ın İnternet Sitesi üzerinde bizzat İnternet Sitesi veya Satıcılar tarafından satışa arz edilen ürün veya hizmetlerin ücretlerini güvenli bir şekilde ödeyebilmelerini, İnternet Sitesi veya Satıcılar’ın da söz konusu ücretleri güvenli bir şekilde tahsil edebilmelerini ve tüm tahsilatlarını izleyip yönetebilmelerini sağlayan çözüm</p>
                                <p>Ödeme Aracı : Alıcı tarafından ödeme emrini vermek için kullanılan kart, cep telefonu, şifre ve benzeri kişiye özel araç</p>
                                <p>Ödeme Hesabı : Satıcı adına iyzico nezdinde açılan ve ödeme işleminin yürütülmesinde kullanılan hesap</p>
                                <p>Ödeme İşlemi : İnternet Sitesi’nde satışa sunulan ürünler veya hizmetler için ödeme yapılması amacıyla, Platform aracılığı ile yürütülen bir dizi operasyon</p>
                                <p>Platform : iyzico tarafından geliştirilen sanal ödeme ve doğrulama ağ geçidi olan bir yazılımdan ibaret sanal platform</p>
                                <p>Pazaryeri : İnternet Sitesi’ni işletmekte olan, kendisi veya yer sağladığı Satıcı tarafından İnternet Sitesi’nde mal veya hizmetleri satışa sunulmasına imkan veren gerçek veya tüzel kişi.</p>
                                <p>Satıcı : Ödeme İşlemi’ne konu fonun ulaşması istenen, İnternet Sitesi üzerinden satış gerçekleştiren satıcı/sağlayıcı</p>
                                <p>Servis : Sözleşme’de belirlenen hüküm ve koşullar çerçevesinde Satıcı’ya sunulacak olan iyzibazaar hizmeti</p>
                                <p>Sistem Ortağı : Platform aracılığı ile ödemelerin işlenmesi konusunda işbirliğinde bulunulan banka veya finans kuruluşu</p>
                                <p>Sözleşme : Satıcı ile akdedilen işbu Sanal Platform Kullanım Çerçeve Sözleşmesi</p>
                                <p>Şüpheli İşlem : Sözleşme ile belirlenen durumlar da dahil olmak üzere, Hatalı/Yetkisiz İşlem olarak değerlendirilme ihtimali bulunan Ödeme İşlemi</p>
                                <p>Yetkili Personel : Satıcı’ya Platform kullanımı hakkında destek vermek ve iletişime geçmek üzere iyzico tarafından yetkilendirilmiş olan personel</p>
                                <p>Yönetim Arayüzü : Satıcı’nın Platform’a ilişkin ayarları yapabilmesi, iletişim bilgilerini değiştirebilmesi ve Sözleşme ile belirlenen kapsamdaki diğer operasyonları
                                    gerçekleştirebilmesini sağlayan Platform’a ilişkin yönetim arayüzü</p>
                                <p>3. SÖZLEŞMENİN KONUSU</p>
                                <p>a) Pazaryeri tarafından işletilmekte olan İnternet Sitesi üzerindeki ödeme hizmetleri iyzico tarafından sunulmaktadır. iyzico, bu kapsamda hem Pazaryeri hem Satıcı hem de Alıcı’ya 6493 sayılı Ödeme ve Menkul Kıymet Mutabakat Sistemleri, Ödeme Hizmetleri ve Elektronik Para Kuruluşları Hakkında Kanun (“Kanun”) ve alt düzenlemeleri uyarınca ödeme hizmeti verecektir. Bu kapsamda iyzico, İnternet Sitesi’nden Alıcı’nın, sipariş verdiği mal veya hizmetin tam ve gereği gibi teslim edildiğine veya ifa edildiğine ilişkin işbu Sözleşme’de belirtilen şekilde onayının alınmasına veya üst sürenin dolmasına kadar Alıcı’dan tahsil edilen parayı Alıcı’nın Ödeme Hesabı’nda tutacak, Alıcı onayına veya süre bitimine müteakip Satıcı’nın Ödeme Hesabına aktaracaktır.</p>
                                <p>b) İşbu Sözleşme, yukarıda belirtilen kapsamda iyzico tarafından Satıcı’ya, İnternet Sitesi üzerinden Pazaryeri aracılığıyla satışa arz ettiği ürün ve hizmetlerin bedellerini tahsil etmesi için sunulan Servis’e ilişkin esaslar ile Taraflar’ın bu kapsamdaki hak ve yükümlülüklerini düzenlemektedir.</p>
                                <p>GENEL ŞARTLAR</p>
                                <p>4.1. KAYIT</p>
                                <p>a) Pazaryeri’nin Satıcı bilgilerini API üzerinden iyzico’ye iletmesi ile iyzico, Satıcı’nın servise kaydını gerçekleştirecektir.</p>
                                <p>b) iyzico’nun, Satıcı bilgilerini onaylaması akabinde Sözleşme’nin Satıcı tarafından onaylandığı tarih itibariyle işbu Sözleşme yürürlük ve geçerlilik kazanacaktır.</p>
                                <p>4.2. KULLANIM KOŞULLARI</p>
                                <p>a) Satıcı Servis’i ancak Sözleşme yürürlüğe girdikten sonra kullanabilecektir.</p>
                                <p>b) iyzico, aşağıda belirtilen konulardaki haklarını saklı tutmaktadır:</p>
                                <p>-Sözleşme yürürlüğe girmeden önce Satıcı’yı telefon ile arama ve Pazaryeri tarafından iletilen bilgileri doğrulama, ek bilgi ve belge talep etme; ve/veya,</p>
                                <p>-Gerekçesini belirterek Satıcı’nın kaydını yapmama.</p>
                                <p>4.3. PLATFORM ÇALIŞMA PRENSİPLERİNE İLİŞKİN ESASLAR</p>
                                <p>4.3.1 Genel Esaslar</p>
                                <p>a) İşbu Sözleşme uyarınca iyzico, Alıcı tarafından İnternet Sitesi’nden sipariş edilen ürün ve hizmetlere ilişkin ödemelerin kabul edilmesi ve işleme alınması ve Satıcı’ya ödemelerin yapılması amacıyla Servis sunmayı kabul ve taahhüt eder.</p>
                                <p>b) iyzico, özellikle Sistem Ortakları tarafından gerçekleştirilen güvenlik standardı değişikliklerinin sonucunda güvenlik standardını değiştirme hakkını saklı tutar.</p>
                                <p>c) Satıcı, Alıcı tarafından yapılan ödemelere ait provizyonların Sistem Ortakları tarafından belirtilen koşullar kapsamında gerçekleştirildiğini bildiğini, Sistem Ortakları’nın sitelerine yönelik ihlâller veya saldırılara (hacking, phishing) yönelik olarak iyzico’nin herhangi bir sorumluluğu bulunmadığını beyan eder.</p>

                                <p>d) Platform ve Sözleşme kapsamındaki hizmetlerden münhasıran Satıcı tarafından faydalanılabilecektir. Bu hükme aykırılık Sözleşme’ye aykırılık teşkil eder ve bu aykırılık Sözleşme’nin iyzico tarafından tek taraflı feshi için yeterli sebep olacaktır.</p>
                                <p>4.3.2 Satıcı’nın Platform’u Kullanımına İlişkin Ek Düzenlemeler</p>
                                <p>a) Satıcı’nın kendi internet sitesi veya başka internet siteleri üzerinden Servis’ten faydalanmak ve Yönetim Arayüzü’nü kullanmak istemesi halinde, bu husus iyzico’ya ayrıca bildirilecek ve iyzico’nin kabulü halinde konu ile ilgili olarak Taraflar arasında ayrıca bir anlaşma akdedilecektir.</p>
                                <p>b) iyzico, Platform’u kullanması için gerekli olan sistem araçlarının Satıcı tarafından uygulamaya sokulmasını sağlayacaktır.</p>
                                <p>c) iyzico, Platform’a ilişkin kullanım desteği verecek olup, Platform’un kurulum, kullanım ve işleyişine ilişkin olarak talimatlar verme yetkisini haizdir.</p>
                                <p>d) Satıcı, Platform’a ve bilgilere üçüncü kişilerce gerçekleştirilen siber saldırı, virüs ve benzeri zararlı ve yetkisiz erişimler halinde derhal iyzico’yi yazılı olarak bilgilendirecektir.</p>
                                <p>e) iyzico, Satıcı’nın, sistem araçlarında değişiklik yapmasına, sistem tarafından öngörülenler dışında işlevlerine müdahalede bulunmasına veya sistem araçlarının kurulum ve kullanım talimatlarının aksine hareket etmesine izin vermemektedir. Satıcı’nın bu hususlara aykırı hareket etmesi, Sözleşme’ye aykırılık teşkil eder.</p>
                                <p>5. SATICI’NIN HAK VE YÜKÜMLÜLÜKLERİ</p>
                                <p>a) Satıcı, Platform üzerinde değişiklik yapmayacağını ve Platform’un işlevlerine müdahale etmeyeceğini, Platform’u kurulum ve kullanım talimatlarına uygun olarak kullanacağını kabul ve beyan eder.</p>
                                <p>b) Satıcı, iyzico tarafından sunulan Platform özelliklerine ilişkin açıklama ile “iyzico Platform Aracılığıyla Ödeme Yapılmasına İlişkin Kurallar”a ve bunlarla ilgili tüm güncellemelere uyacak, uymaması nedeniyle meydana gelecek tüm taleplerden sorumlu olacaktır.</p>
                                <p>c) Satıcı, İnternet Sitesi’nde satışı yasal olmayan ürünler ve hizmetler listelemeyecek/sunmayacaktır. iyzico tarafından, İnternet Sitesi’nde satışı hukuka aykırı olan ya da iyzico ilkelerine ters düşen, özellikle aşağıda belirtilen ürünlerin veya hizmetlerin sunulduğunun tespiti hâlinde, Platform’un kullanılmasını tamamen veya kısmen durdurma yetkisi vardır. Alıcı da aynı şekilde Servis ve Platform’u yasalara veya ahlaka aykırı ürün ve hizmet temin etmek amacıyla ve/veya yasalara veya ahlaka aykırı amaçlarla kullanmayacaktır. Bu kapsamda Servis, özellikle aşağıda yer alan ürün ve hizmetlerin satışında ve temininde kullanılamaz:</p>
                                <p>- Pornografik ürünler veya erotik nitelikteki hizmetler,</p>
                                <p>- Çocuk pornografisi gösteren veya teşvik eden ürünler ve pornografi dağıtımı suçunun işlendiğine dair işaretler gösteren diğer cinsel uygulamalar,</p>
                                <p>- Uyuşturucu ve psikotropik maddelerin veya zehirlerin yaygınlaştırılması,</p>
                                <p>- Reçeteli verilen ilâçlar,</p>
                                <p>- Suça teşvik edebilecek veya neden olabilecek veya telif hakkı korumalarını teknik yollarla ortadan kaldıran ürün ve hizmetler,</p>
                                <p>- Terör mevzuatı kapsamına giren ürün ve hizmetler,</p>
                                <p>- Üçüncü şahıslar nezdinde iyzico’nin itibarını zedeleyebilecek biçimde hakaret, sövme içeren diğer ürünler veya hizmetler,</p>
                                <p>- Bahis borçları veya kumar kazançları için kumar faaliyetinin yeri ve türünden bağımsız ödemeler,</p>
                                <p>- Üçüncü kişilerin fikrî ve sınaî mülkiyet haklarını ihlâl eden ürünler.</p>
                                <p>d) Yukarıda sayılan sebeplere bağlı olarak Ödeme İşlemi’nin reddedilmesi veya Platform’a erişimin tamamen askıya alınması Sözleşme’nin iyzico tarafından ihlâlini teşkil etmez.</p>
                                <p>e) Yukarıda yer alan hususlar nedeni ile oluşabilecek tüm sorumluluk Satıcı’ya ait olup, iyzico’nun her türlü zararlarını ferileri ile birlikte Satıcı’ya rücu hakkı saklıdır. Satışı veya temini hukuka aykırı olan ya da iyzico ilkelerine ters düşen ürünlerin ve hizmetlerin satışı veya temini sonucunda iyzico’nin bir zarara uğraması hâlinde, Satıcı iyzico’nin uğradığı her türlü zararı nakden ve defaten ilk talep ile tazmin etmekle yükümlüdür.</p>
                                <p>f) Satıcı, İnternet Sitesi’nde sunulan/temin edilen ürünler veya hizmetler ile Servis kapsamındaki işlemler hakkında talep halinde iyzico’ye bilgi sağlamakla yükümlüdür. Satıcı’nın bu hüküm gereğince bilgi sağlamaması hâlinde, iyzico, bilgisi verilmeyen ürün ve hizmetlerin ödemesine konu olan işlemi yapmayı reddetmek ve bilgi sağlanmaması halinde Satıcı’nın Platform’a erişimini askıya almak yetkisini haizdir.</p>
                                <p>g) Satıcı, İnternet Sitesi’nde sunduğu ürünlerin ve hizmetlerin işbu maddede belirtilenler arasında yer alıp almadığını, kanunlar tarafından satışı yasaklanmış ürün veya hizmet olup olmadığını ve ürünlerin ve hizmetlerin mevzuata uygun olarak satışının yapılıp yapılmadığını kontrol ve temin etmekle yükümlüdür.</p>
                                <p>h) Satıcı, İnternet Sitesi üzerinden satılan her ürün ve/veya hizmet için vergi mevzuatı kapsamında belgelendirmeye dair tüm yükümlülüklerini yerine getirecektir.</p>
                                <p>i) Satıcı, Hassas Ödeme Verileri’nin gizliliğinin ve güvenliğinin sağlanması hususunda gerekli önlemleri alacaktır. Satıcı, kendi nezdinde Hassas Ödeme Verisi tutmayacak, işlemeyecek ve kaydetmeyecek, önemli güvenlik olaylarında iyzico’yu bu durumdan derhal haberdar edecektir.</p>
                                <p>j) Satıcı, kendisine veya üçüncü bir kişiye ait ödeme kartı kullanılarak kazanç elde etmek amacıyla sanal POS cihazları aracılığıyla İnternet Sitesi üzerinden gerçek iradelerine uymayacak şekilde işlem yaparak kendilerine yahut üçüncü kişilere yarar sağlayıcı nakit satışı niteliği taşıyan işlemlerde bulunmayacağını kabul, beyan ve taahhüt eder Bu tür bir işlemin iyzico veya resmi merciler tarafından tespit edilmesi durumunda, iyzico tek taraflı ve derhal etkili olacak şekilde sanal POS’ların kullanımını durdurma ve Sözleşme’yi sözleşmeye aykırılıktan dolayı feshetme hakkına sahiptir. Bu durumda Sözleşme’nin feshedilip edilmediğine bakılmaksızın iyzico’nin her türlü
                                    zararını talep hakkı saklıdır.</p>
                                <p>6. iyzico’NUN HAK VE YÜKÜMLÜLÜKLERİ</p>
                                <p>6.1. iyzico’nin Platform’a Erişimi
                                    Engelleme Hakkı</p>
                                <p>a) iyzico, özellikle aşağıdaki durumların meydana gelmesi halinde, Platform’a erişimi engelleme hakkına sahip olacaktır. Söz konusu durumun ortadan kaldırılmasını müteakip erişim tekrar sağlanacaktır.</p>
                                <p>- Platform'a yönelik bilgisayar virüsü tehdidi varsa,</p>
                                <p>- Satıcı işbu Sözleşme kapsamında kendisinden talep edilen bilgileri (Satıcı açısından kendisi tarafından Alıcı’ya sunulması gereken bilgiler dahil)
                                    sağlamıyorsa,</p>
                                <p>- Servis’in 5(c) maddesine aykırı kullanıldığı tespit edilirse,</p>
                                <p>b) İşbu maddenin (a) bendinde sayılan durumlar Satıcı tarafından 3 gün içinde düzeltilmez veya söz konusu durumlar 2 ay içinde birden fazla defa tekrar eder ise iyzico Platform’a erişimi askıya alma hakkına sahiptir. Platform’un askıya alınması sebebi ortadan kalktığında iyzico yapılacak güvenlik denetimi sonrasında Platform’u tekrar kullanıma açar.</p>
                                <p>6.2. Platform Bakımı, Kesintiler ve Arıza Çözümleri</p>
                                <p>a) iyzico, Platform’un düzgün olarak çalışması için gerekli olan sürekli bakımı, donanımı ve teknik desteği sağlayacaktır. Bununla bağlantılı olarak iyzico’nin, işbu Sözleşme’de açıkça belirtilen durumlarda ilgili sunucuların çalışmasını geçici olarak durdurma veya sınırlandırma hakkı saklıdır. Bu durumda, Satıcı’nın herhangi bir tazminat hakkı mevcut değildir.</p>
                                <p>b) İşbu Sözleşme’de açıkça belirtilen durumlar haricinde, gerekli bakım, güncelleme ve benzeri hususlar için iyzico, yapacağı kesintileri işgünleri dışındaki günlerde özellikle akşam veya gece saatlerinde (01:00 - 06:00 saatleri arasında) gerçekleştirmek için azami özen gösterecek olup, acil durumlarda bu gün ve saatler dışında da kesinti yapılabilecektir. Bu halde Pazaryeri en kısa süre içerisinde acil durum ve kesintiye ilişkin detayları Satıcı’ya bildirilecektir.</p>
                                <p>c) iyzico, acil durumlar dışında e-posta mesajı göndererek Satıcı’yı gerekli önlemleri almasını sağlayacak şekilde kesinti hakkında önceden bilgilendirebilecektir.</p>
                                <p>d) iyzico, Platform’un kesintisiz çalışacağını garanti etmemektedir. iyzico, ödemeleri zamanında işleyecek olup, Sistem Ortakları’ndan kaynaklanan sorunlar nedeniyle, bu işlemlerin zamanında gerçekleşmemesinden sorumlu olmamakla birlikte, söz konusu sorunların en kısa süre içerisinde giderilmesi için gayret edecek ve Sistem Ortakları ile iletişim halinde olacaktır.</p>
                                <p>6.3. Kişisel Bilgilerin Korunması</p>
                                <p>Satıcı, kendisine ait bilgilerin Servis’in verilmesini temin amacıyla iyzico Gizlilik Kişisel Veri Politikası’nın <a href="https://www.iyzico.com/gizlilik-politikasi/">https://www.iyzico.com/gizlilik-politikasi/</a> adresinde yayınlanan en güncel halinde belirtildiği şekilde iyzico tarafından işlenmesini, saklanmasını ve benzeri işlemlerin (sisteme tanımlamak ve kayıt etmek) yapılmasına dair bilgilendirildiğini kabul etmektedir. iyzico kişisel verilerin “gizli bilgi” olduğunun, kendisine bu amaçla verilen kişisel bilgilerin gizliliğini temin için gerekli özeni göstermekle yükümlü olduğunun ve 6698 sayılı Kişisel Verilen Korunması Kanunu’na ve diğer güncel mevzuatlara
                                    uygun davranacağının bilincindedir.</p>
                                <p>7. ŞİKÂYET PROSEDÜRÜ, HATA VE ZARAR SORUMLULUKLARI</p>
                                <p>7.1. ŞİKÂYET PROSEDÜRÜ</p>
                                <p>a) Satıcı, iyzico tarafından sağlanan hizmetlere ilişkin şikâyetleri aşağıda belirtilen şekillerde iyzico’ya haber verecektir:</p>
                                <p>- <a href="mailto:sikayet@iyzico.com">sikayet@iyzico.com</a>e-posta adresine veya</p>
                                <p>- iyzico’nun Burhaniye Mah. Atilla Sok. No:7 Üsküdar İstanbul adresine iadeli taahhütlü posta göndermek suretiyle,</p>
                                <p>b) iyzico, şikâyet konusu sorunun giderilmesi için elinden gelen en iyi çabayı sarf edecektir. iyzico, söz konusu sorunların giderilmesi sürecinde destek verecek çalışanların kalifiye elemanlar olduğunu kabul, beyan ve taahhüt eder. iyzico, şikâyetlerdeki eksiklikler (bildirim eksiklikleri) ile bağlantılı olarak meydana gelen gecikmelerden sorumlu olmayacaktır.</p>
                                <p>c) Satıcı tarafından yöneltilecek şikâyetler şu ayrıntıları içereceklerdir: Şikâyet nedeni, işlemde dahil edilen tarafların listesi, varsa işlem kodu ve sorunun ayrıntılı bir listesi ve olası hata mesajlarının içeriği.</p>
                                <p>d) Satıcı, Platform ve Ödeme İşlemleri ile ilgili olarak Alıcı tarafından iletilen şikâyetleri üçüncü kişiler ile paylaşmayacak ve şikâyetin doğrulanması ile yükümlü olacaktır. Satıcı, doğrudan kendisine iletilen taleplerle ilgili olarak, sorun Servis’ten kaynaklanmadığı sürece, kendisine iletilen şikâyetleri iyzico’ya yönlendirmeyecektir.</p>
                                <p>e) Satıcı ile herhangi bir Alıcı arasında meydana gelen uyuşmazlıklar ilgili işlemin tarafı olan Alıcı ve Satıcı arasında çözüme ulaştırılacak olup, iyzico bu
                                    işlemlerden veya uyuşmazlıklardan sorumlu olmayacaktır. iyzico’nin bu madde kapsamında herhangi bir nedenle (kendi kusurundan kaynaklı haller dışında) bir bedel ödemek durumunda kalması halinde Satıcı bunu derhal tazmin edecektir.</p>
                                <p>f) Şikâyetler, iyzico tarafından kendisine ulaşma tarihinden itibaren en geç 20 (yirmi) gün içerisinde yanıtlanacaktır.</p>
                                <p>7.2. HATA VE ZARARDAN DOĞAN SORUMLULUK</p>
                                <p>a) iyzico, İnternet Sitesi’nde sunulan ürünlerin veya hizmetlerin Alıcı’ya tedarik edilmesine veya iade edilmesine katılmayacaktır. Bu nedenle Platform aracılığıyla ödemesi yapılan ürünler veya hizmetlerden veya bu ödemesi yapılan ürünler veya hizmetlere ilişkin Alıcı ile Satıcı veya Alıcı ile Pazaryeri arasındaki sözleşmenin hukuka uygun bir şekilde akdedilmiş olmasından iyzico sorumlu olmayacaktır.</p>
                                <p>b) iyzico, sadece Sözleşme’den kaynaklanan yükümlülüklerini ihlâl etmesi hâlinde meydana gelen doğrudan zararlardan sorumlu olup, kendi kusurunun bulunmadığı üçüncü şahıs veya Sistem Ortakları tarafından neden olunan zararlardan sorumlu olmayacaktır.</p>
                                <p>c) iyzico, ödeme emrinin verilmesinin ardından Satıcı tarafından banka hesap bilgilerinin hatalı veya eksik girilmesi nedeniyle işlemlerin tamamlanmamasından veya gecikmesinden sorumlu olmayacaktır. iyzico, kendisi tarafından öngörülemeyen veya engellenemeyen durumlar neticesinde meydana gelen gecikmelerden ötürü, Ödeme İşlemi’nin gerçekleştirilememesinden veya Ödeme İşlemi’nde kendi kusuru dışında hata meydana gelmesinden veya bunların sonucunda meydana gelen zararlardan sorumlu olmayacaktır.</p>
                                <p>d) Satıcı’nın işbu Sözleşme kapsamındaki herhangi bir taahhüt veya yükümlülüğüne aykırı davranması, yasaları veya herhangi bir üçüncü kişinin haklarını ihlal etmesi nedeniyle iyzico’nun, görevlilerinin, yöneticilerinin ve çalışanlarının bir zarara uğraması yahut yasal, idari veya cezai bir yaptırıma tabi tutulması halinde ilgili tutarlar (avukatlık ücretleri de dahil) ilk talepte ödenmek üzere ferileri ile birlikte Satıcı’ya rücu edilecek, ilgili tüm üçüncü kişi talepleri ise iyzico’ya yönlendirilecektir. iyzico’nun bahsi geçen tutarları Satıcı’ya yapılacak ödemelerden mahsup hakkı saklıdır.</p>
                                <p>e) Satıcı, işbu Sözleşme’nin 4.3.1(d), 7.2(d) ve 7.3(h) maddelerine aykırı davrandığı takdirde iyzico’ya 25.000 TL tutarında bir cezai şart ödemekle yükümlü olacaktır. iyzico, cezai şart tutarını Satıcı’ya yapılacak ödemelerden mahsup edebilir. Satıcı, iyzico tarafından riskli olarak nitelendirilen ve 4.3.1(d), 7.2(d) ve 7.3(h) maddelerinde tanımlanan durumlarda iyzico’nin işbu Sözleşme kapsamında Satıcı’ya ödenmesi gereken tutarları ödemeyi reddedebileceğini kabul ve beyan eder. iyzico’nun cezai şart tutarını aşan zararlarını talep hakkı saklıdır.</p>
                                <p>7.3. ŞÜPHELİ/YETKİLENDİRİLMEMİŞ/HATALI İŞLEMLERDE SORUMLULUK</p>
                                <p>a) Alıcı tarafından ödemenin iyzico’ya iletilmesi halinde iyzico işbu Sözleşme’de belirtilen koşullarda ve Pazaryeri tarafından belirtilen kurallar dahilinde ilgili onay süreçlerinin tamamlanmasını müteakip ödemeyi Satıcı’ya aktaracaktır. Alıcı tarafından ödemenin iyzico’ya aktarılmaması halinde, iyzico’nin Satıcı’ya ödeme yapma yükümlülüğü söz konusu olmayacaktır. </p>
                                <p>b) Satıcı, iyzico’nun Alıcı tarafından iyzico’ya gönderilen tutarları Satıcı’ya aktarma yükümlülüğünün işbu 7.3. maddede belirtilen onay anı itibariyle başlayacağını ve işbu Sözleşme’de belirtilen süre ve koşullarda yerine getirileceğini kabul ve beyan eder. Alıcı tarafından gerekli onayların verilmemesi ve/veya Pazaryeri onay sürecinin herhangi bir nedenle gereği gibi tamamlanmaması halinde iyzico ilgili tutarı Alıcı’ya iade edebilir.</p>
                                <p>c) Alıcı tarafından ürün veya hizmetin tam ve gereği gibi teslim edildiğine/sunulduğuna ilişkin olarak Pazaryeri kuralları kapsamında bir onay verildiği veya
                                    Pazaryeri tarafından öngörülen prosedüre göre onay süresi tamamlandığı anda Alıcı ilgili Ödeme İşlemi’ne ilişkin ödeme emrini vermiş kabul edilir. Alıcı ürün veya hizmetin tam ve gereği gibi teslim edilmediğine ilişkin bir bildirim yaptığı takdirde Pazaryeri ve/veya Alıcı tarafından iyzico’ya yapılacak bildirim doğrultusunda ilgili tutar Alıcı’ya iade edilebilecek; Pazaryeri tarafından belirlenen usul ve sürelerde herhangi bir onay veya red bildirimi yapılmadığı takdirde ise Alıcı’nın mal veya hizmeti tam ve gereği gibi teslim aldığı kabul edilecek ve ilgili tutar yine Satıcı hesabına aktaracaktır. </p>
                                <p>d) Herhangi bir işleme ilişkin olarak iyzico’ye Hatalı/Yetkisiz İşlem bildiriminde bulunulduğu takdirde, derhal ve her halükarda Ödeme İşlemi’nin gerçekleştirilmesini takip eden 13 (onüç) ay içerisinde Alıcı tarafından harcama itirazı (chargeback) talebinde bulunulabilecektir. Bu durumda ilgili işlem bedeli Satıcı’ya aktarılmayarak iyzico tarafından doğrudan Alıcı’nın ödeme hizmeti sağlayıcısına iade edilebilecek, bildirim anında işlem bedeli Satıcı’ya aktarılmış ise iyzico ilgili tutarları Satıcı’dan iade talep ederek (Satıcı iadeyi 1 gün içerisinde gerçekleştirecek olup iyzico’nun ilgili bedeli Satıcı’ya yapılacak ödemelerden mahsup hakkı saklıdır) Alıcı’nın ödeme hizmeti sağlayıcısına aktaracaktır. </p>
                                <p>e) iyzico, özellikle aşağıdaki durumlar olmak üzere Şüpheli İşlemler’de ve Alıcı veya Sistem Ortağı tarafından kendisine bildirilmesi hâlinde, işlem tutarlarını Sistem Ortağı veya Alıcı’nın Ödeme İşlemi’ne ilişkin onayı verme tarihine kadar saklama ve Satıcı’ya ödeme yapmama hakkına sahiptir. Şüpheli durumun belgelendirilmek kaydıyla kesinleşmesi halinde ödemeler kesin olarak işlenmeyecektir.</p>
                                <p>- Ödeme İşlemi’nin yasal hükümlere uygun olmadığına yönelik bir şüphe varsa,</p>
                                <p>- Ödeme İşlemi’nin, Ödeme İşlemi’nde kullanılan kredi kartının hamilinin bilgisi dışında yapıldığına yönelik bir şüphe varsa,</p>
                                <p>- Ödeme İşlemi’nin, Ödeme İşlemi’nde kullanılan banka hesabı sahibinin bilgisi dışında yapıldığına yönelik bir şüphe varsa,</p>
                                <p>- Ödeme İşlemi’nin gerçek bir Ödeme İşlemi olmadığına (testler hariç) yönelik bir şüphe varsa.</p>
                                <p>f) Yukarıda belirtilen şekilde Hatalı/Yetkisiz İşlemler veya Şüpheli İşlemler ile Alıcı’nın ürün iadesi gerçekleştirerek geri ödeme talep etmesi nedeniyle iyzico’nun
                                    Sistem Ortağı veya Alıcı’ya herhangi bir şekilde geri ödeme veya zarar tazmininde bulunması veya ilgili idari kurumlar nezdinde idari yaptırıma tabi olması halinde uğrayacağı tüm zarar ve ziyan Satıcı’ya rücu edilecek ve Satıcı tarafından iyzico’nun ilk talebine istinaden tüm ferileri ile birlikte ödenecektir. iyzico’nun bahsi geçen durumlarda ilgili bedelleri Satıcı’ya yapılacak ödemelerden mahsup hakkı saklıdır.</p>
                                <p>g) İşbu Madde 7.3 kapsamında gerçekleşen Hatalı/Yetkisiz/Şüpheli iade işlemlerinin tekrarı halinde iyzico’nun Satıcı’nın üyeliğini askıya alma yahut sonlandırma hakkı saklıdır.</p>
                                <p>h) Ödeme Hizmetleri ve Elektronik Para İhracı ile Ödeme Kuruluşları ve Elektronik Para Kuruluşları Hakkında Yönetmelik Madde 45 uyarınca; kayıp veya çalıntı Ödeme Aracı’nın kullanılması ya da Alıcı’nın kişisel güvenlik bilgilerinin gereği gibi muhafaza edilmemesi nedeniyle gerçekleşen yetkisiz işlemin, Alıcı tarafından kanıtlanması halinde veya Satıcı kusurundan kaynaklanması halinde, Satıcı; Alıcı, iyzico ve Pazaryeri’nin zararını tazmin edecek ve yetkisiz bir şekilde tahsil edilen tutarları Alıcı’ya iade edilmek üzere iyzico’ya aktaracaktır. İşlem kapsamında kusur tespitinin mümkün olmaması halinde ise iyzico’nun Alıcı veya diğer bir üçüncü kişiye ödemek zorunda kalacağı bedeller Satıcı’dan tahsil edilecektir. iyzico’nun bu bedelleri Satıcı’ya yapılacak ödemelerden mahsup hakkı saklıdır.</p>
                                <p>i) Herhangi bir Ödeme Aracı’nı kullanan kişinin o Ödeme Aracı’nı kullanmaya yetkili olan veya işlemi gerçekleştirmek için bilgileri bulunan kişi olmadığı
                                    yönünde haklı bir kanaati oluşması halinde Satıcı, ilgili Alıcı’nın yetkilendirmelerini inceleyecek ve işlemin hileli olduğuna kanaat getirdiği takdirde ödemeyi kabul etmeyecektir. Satıcı, bu durumda derhal iyzico’yu bilgilendirmekle yükümlüdür.</p>
                                <p>8. SATICI’NIN iyzico LOGOSUNU KULLANIMINA İLİŞKİN KOŞULLAR</p>
                                <p>a) Satıcı yapacağı her türlü tanıtımda iyzico ismini, logosunu, iyzico’nin yazılı müsaadesi olmadan kullanmayacağını kabul, beyan ve taahhüt eder.</p>
                                <p>b) iyzico, Platform’u ve kendi web sitesinin içeriğini ve tasarımını verilen hizmeti aksatmamak şartıyla değiştirme hakkını saklı tutar.Böyle bir durumda iyzico değiştirilen materyalleri Satıcı’nın kullanımına açacaktır.</p>
                                <p>9. ÖDEMELERE İLİŞKİN ESASLAR</p>
                                <p>9.1. GENEL ESASLAR</p>
                                <p>a) iyzico, Sözleşme kapsamında Alıcı tarafından kendisine iletilen bedellerin, Madde 7.3(c) uyarınca ödeme emrinin verildiği kabul edilen tarihi takip eden iş günü içerisinde Satıcı’ya aktarılmasından sorumludur. </p>
                                <p>b) İşbu Sözleşme kapsamında iyzico tarafından sunulacak Servis kapsamında iyzico her bir işlem tutarından Satıcı’nın Pazaryeri ile akdettiği Üyelik Sözleşmesi kapsamında kesilecek hizmet bedeli komisyonunu düştükten sonra ilgili tutarı yukarıda belirtilen süre içerisinde Satıcı’ya aktaracaktır.</p>
                                <p>c) iyzico, ücretlendirme koşullarını tek taraflı olarak değiştirme yetkisini haizdir.</p>
                                <p>d) Satıcı, iyzico’nun bir banka, kredi veya finans kurumu olmadığını ve iyzico tarafından işbu Sözleşme uyarınca verilen hizmetin bir bankacılık hizmeti olmadığını, iyzico’nin elektronik para kuruluşu olarak Kanun kapsamında ödeme hizmetleri sunduğunu kabul eder.</p>
                                <p>Bu kapsamda iyzico, Ödeme İşlemi kapsamında tahsil edilen tutarlara faiz işletmeyecek yahut Ödeme Aracı ihracında bulunmayacak olup Satıcı iyzico’dan faiz veya sair adlar altında herhangi bir menfaat talebinde bulunmayacaktır.</p>
                                <p>iyzico Satıcı’ye kredi verme, taksitlendirme, tahsil edilemeyen tutarlara ilişkin ödeme veya ödeme garantisi verme yahut bu anlama gelecek faaliyetlerde bulunamaz. Satıcı, iyzico’dan bu kapsamda talepte bulunmamayı kabul ve taahhüt eder. Bununla birlikte Satıcı kendisi taksitlendirme yaptığı takdirde, taksit bedellerinin ödenmesine ilişkin
                                    ödeme hizmeti sunulabilecektir.</p>
                                <p>9.2. ÖDEME İŞLEMLERİNE İLİŞKİN ESASLAR</p>
                                <p>a) iyzico tarafından aktarım yapılmasına rağmen Sistem Ortağı veya ilgili banka tarafından Satıcı’ya ödeme yapılmaması halinden iyzico sorumlu değildir.</p>
                                <p>b) Ödemenin gerçekleştirilmesi için, ilgili Sistem Ortağı’nın ödemeye ilişkin provizyon vermesi gerekmektedir. Satıcı, iyzico’ya Platform kullanılarak yapılan her bir İşlem için provizyon alınmış olunması ve İşlem “tamamlandı” durumuna geçmiş olunması kaydı ile Komisyon Ücreti ödeyecektir. Alıcı’nın Platform aracılığıyla işleme konu tutarı transfer etmesi ve Sistem Ortağı tarafından olumlu provizyon alınması dahil olmak üzere Sistem Ortakları tarafından talep edilen tüm işlemlerin uygun bir şekilde gerçekleştirilmesi hâlinde, İşlem “tamamlandı” durumu atanacaktır.</p>
                                <p>c) Banka ve kredi kartları ile yapılan online ödemeler; Satıcı’nın Sözleşme’de belirtilen hesabına Sistem Ortağı tarafından yatırılacaktır. Satıcı Pazaryeri’ne veya iyzico’ya yazılı olarak bildirdiği hesabın talep edildiğinde kendisine ait olduğunu belgelemekle yükümlüdür. Hesap numarası değişiklikleri ancak Satıcı’nın açıkça temsile yetkili kişisinin yazılı talimatı ile gerçekleştirilebilir.</p>
                                <p>d) iyzico’ya işlemle ilgili olarak olumsuz bir provizyon verilmesi hâlinde, Satıcı konu hakkında bilgilendirilecek ve İşlem’e, varsa Sistem Ortağı tarafından İşlem’in neden tamamlanmadığını gösteren nedenle birlikte uygun durum atanacaktır.</p>
                                <p>e) İnternet Sitesi üzerinden sunulan ürün ve hizmetlere ilişkin ücretlendirme Satıcı tarafından yapılmakta olup Satıcı iyzico’nun bu kapsamda herhangi bir kontrol veya sorumluluğu olmadığını kabul eder.</p>
                                <p>10. SÖZLEŞMENİN SÜRESİ VE FESİH</p>
                                <p>a) İşbu Sözleşme Madde 4.1(b)’de belirtilen tarihte yürürlüğe girecek olup taraflarca feshedilmedikçe yürürlükte kalacaktır.</p>
                                <p>b) Taraflar, işbu Sözleşme’den doğan yükümlülüklerini yerine getirmediği takdirde, diğer Taraf, söz konusu aykırılığın giderilmesi için karşı Taraf’a göndereceği bir ihtar ile aykırılığın giderilmesi için 14 (ondört) gün süre verecek olup, aykırılığın bu süre içerisinde giderilmemesi halinde Sözleşme başka bir ihtara gerek olmaksızın feshedilmiş sayılacaktır.</p>
                                <p>c) Satıcı, işbu Sözleşme’yi, herhangi bir sebep bildirmeksizin, her zaman 1 (bir) ay öncesinden yazılı fesih ihbarında bulunmak kaydıyla feshedebilecektir. iyzico ise, Sözleşme’yi 2 (iki) ay öncesinden yazılı bildirimle herhangi bir sebep göstermeksizin ve tazminat ödemeksizin feshi hakkına sahip olacaktır. Sözleşme’nin fesih tarihinden önce muaccel olan işbu Sözleşme’ye konu yükümlülüklerin yerine getirilmesine halel getirmeyecek olup, Taraflar’ın fesih tarihine kadar muaccel olan alacak hakları saklıdır.</p>
                                <p>d) iyzico’nun işbu Sözleşme kapsamındaki Servis’i sunmasına imkan tanıyan izin ve lisansların herhangi bir şekilde ortadan kalkması ve/veya Pazaryeri ile iyzico arasındaki İnternet Sitesi üzerinden yapılan satışlara ilişkin bedellerin tahsiline ilişkin anlaşmanın sona ermesi halinde işbu Sözleşme kendiliğinden sona erecektir. Satıcı, bu sona erme nedeniyle iyzico’dan tahakkuk etmiş alacakları dışında herhangi bir talep hakkı olmayacağını kabul eder.</p>
                                <p>e) İşbu Sözleşme süresince herhangi bir zamanda Satıcı’nın acze düşmesi, iflas, iflasın ertelenmesi, kayyum tayini ve konkordato ile ilgili prosedürlere konu olması ya da faaliyetlerini fiili olarak durdurması ya da faaliyet konusunu (Satıcı’nın sağlamakta olduğu ürün ve hizmetler dahil) esaslı bir şekilde değiştirmesi, mal varlığının tümünü ya da önemli bir bölümünü elden çıkarması halinde, iyzico işbu Sözleşme kapsamındaki hizmetlerini derhal durdurarak Sözleşme’yi herhangi bir tazminat ödemeksizin feshedebilecektir.</p>
                                <p>f) iyzico hileli veya yetkisiz kullanım şüphesinin söz konusu olduğu hallerde Servis’i askıya alabilecek, Platform’u kullanıma kapatabilecektir. Bu durumda iyzico, ilgili mevzuatta bilgi verilmesini engelleyici düzenlemeler bulunmaması veya güvenliği tehdit edici objektif nedenler olmaması kaydı ile Satıcı’yı konu ile ilgili bilgilendirecek ve askıya alınma sebebi ortadan kalktığında Servis ve Platform’u yeniden Satıcı’nın kullanımına sunacaktır.</p>
                                <p>11. ÇEŞİTLİ HÜKÜMLER</p>
                                <p>a) iyzico tarafından hizmetlerin sağlanmasına yönelik olarak www.iyzico.com internet sitesinde ilân edilecek şartlar ve koşullar, işbu Sözleşme’nin eki ve ayrılmaz bir parçasını teşkil etmektedir. İşbu Sözleşme iyzico’nun www.iyzico.com internet sitesinde veya bağlantılı adreslerinde her zaman Satıcı tarafından erişilebilir olacaktır</p>
                                <p>b) İşbu Sözleşme’den kaynaklanan her türlü resim, harç ve vergi Taraflarca eşit olarak ödenecektir.</p>
                                <p>c) Taraflar işbu Sözleşme’den kaynaklanan doğmuş veya doğacak olan alacakları diğer Taraf’ın yazılı izni olmaksızın hiçbir surette üçüncü kişilere devir veya temlik edemez.</p>
                                <p>d) iyzico, Sözleşme’deki her türlü değişikliği, internet sitesinde ilân edebilir ve/veya yeni sürümlerini yayınlayabilir. Değişikliklere ilişkin olarak iyzico, değişikliğin kapsamı, yürürlük tarihi ve Satıcı’nın fesih hakkına ilişkin bilgileri içeren bildirimi yürürlüğe girme tarihinden 30 (otuz) gün önce Satıcı’ya iletir. Bu durumda Satıcı’nın Sözleşme’yi herhangi bir ücret ödemeksizin feshetme hakkı saklı olup belirtilen 30 (otuz) günlük süre içinde itiraz edilmemesi halinde değişiklik kabul edilmiş sayılacaktır.</p>
                                <p>e) Taraflar’ın, kendi iradeleri dışında gerçekleşen, müdahale imkanları bulunmayan ve makul bir şekilde önceden öngörülmesi mümkün olmayan nedenlerle yükümlülüklerini yerine getiremedikleri savaş, sıkıyönetim, seferberlik, terörist eylemler, doğal afetler, yangın, grev ve lokavt da dahil istisnai olaylar mücbir sebep olarak kabul edilir. Mücbir sebebin ortaya çıkması halinde, Sözleşme’ye ilişkin edimler mücbir sebep hali sona erinceye kadar askıya alınır. Askıya alınma süresi 1 (bir) ayı geçtiği takdirde, Taraflar’ın işbu Sözleşme’yi fesih hakkı doğar.</p>
                                <p>f) Satıcı, kanunlara ve VISA, MasterCard ve diğer ödeme kartı kuruluş ve otoritelerinin (B.D.D.K., T.C.M.B. vb) kuralları ile iyzico tarafından hazırlanan kurallara ve prosedürlere uyacaktır.</p>
                                <p>g) Satıcı, satışa arz ettiği ürünü/ürünleri gerek Banka Kartları ve Kredi Kartları Kanunu ve bu Kanun uyarınca düzenlenen Banka Kartları ve Kredi Kartları Hakkında Yönetmelik hükümlerine gerekse 6502 sayılı Tüketicinin Korunması Hakkında Kanun veya diğer ilgili mevzuat hükümlerini dikkate alarak uygun ve doğru kategoride listelemekle ve ürünle ilgisi olmayan kelimeleri kullanmamakla yükümlüdür. Satıcı’nın, gerek iyzico ile imzaladığı sözleşmeye gerek Banka Kartları ve Kredi Kartları Kanunu ve bu Kanun uyarınca düzenlenen Banka Kartları ve Kredi Kartları Hakkında Yönetmelik hükümlerine gerekse 6502 sayılı Tüketicinin Korunması Hakkında Kanun hükümlerine veya diğer ilgili mevzuat hükümlerine aykırı olarak listelemesi ve ilgili ürünlerin B.D.D.K.’nın ilgili mevzuatı dışında taksitlendirilmiş olması nedeniyle iyzico’nun maruz kalabileceği idari yaptırımlar ve cezalar dahil her türlü zarar ve ziyandan Satıcı bizzat sorumludur.</p>
                                <p>h) iyzico tarafından Satıcı’nın ürünü/ürünleri yanlış kategorilendirdiğinin veya ürün/ürünlerle ilgili olarak yanıltıcı bilgi ve/veya kelimeler verdiğinin tespit edilmesi halinde, iyzico işbu Sözleşme’yi tek taraflı olarak feshetme hakkına sahiptir. iyzico'nun Sözleşme’yi tek taraflı feshetmesi nedeniyle Satıcı’nın iyzico’ dan zarar ve ziyan talep etmesi söz konusu değildir.</p>
                                <p>i) İşbu Sözleşme’nin herhangi bir hükmünü herhangi bir nedenle geçersiz olması hâlinde, diğer hükümlerin veya Sözleşme’nin uygulanabilirliği ve/veya geçerliliği bu geçersizlikten etkilenmeyecektir.</p>
                                <p>j) Taraflar, Platform üzerinden erişilebilir kayıtların Taraflar arasında delil sözleşmesi mahiyetinde kabul edileceği hususunda mutabıktır.</p>
                                <p>k) Taraflar işbu Sözleşme’den doğacak uyuşmazlıkların çözümünde İstanbul Anadolu Mahkemelerinin ve İcra Dairelerinin yetkisini kabul etmişlerdir.</p>
                                <p>l) Taraflar, işbu Sözleşme’de belirtilen adreslerinde meydana gelen değişiklikleri karşı tarafa yazılı olarak bildirmedikleri takdirde, işbu sözleşmede belirtilen adreslere yapılacak tebligat ve bildirimler geçerli tebliğ hükmünde olacaktır. iyzico, işbu Sözleşme kapsamında Satıcı’ya yönelik yapacağı bildirimleri Sözleşme’de belirtilen zamanlarda Satıcı’nın belirtilen adresine iletilecek e-posta aracılığıyla yapacaktır. Ancak Türk Ticaret Kanunu’nun 18/3 maddesi uyarınca, karşı tarafı temerrüde düşürmeye veya Sözleşme’yi feshetmeye ilişkin bildirimler, noter aracılığıyla, taahhütlü mektupla, telgrafla veya güvenli elektronik imza kullanılarak kayıtlı elektronik posta sistemi ile yapılacaktır.</p>
                        </div>


                </section>
          </React.Fragment>
        )
    }
}